name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download .NET Framework 4.8 Developer Pack
      run: |
        $url = 'https://github.com/WiizRDz/dotnet-packages/raw/main/NDP48-KB4486129-x86-x64-AllOS-ENU.exe'
        $output = 'dotnet_framework.exe'
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList '/q' -Wait

    - name: Setup .NET Framework 4.8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # specify your tag name
        release_name: Release v1.0.0  # specify your release name
        body: |
          Release notes for v1.0.0:
          - Describe your changes here
        draft: false
        prerelease: false
