name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download .NET Framework 4.8 Developer Pack
      run: |
        $webClient = New-Object System.Net.WebClient
        $url = 'https://download.visualstudio.microsoft.com/download/pr/7e8e0667-d6ae-4c38-a2b7-96007232f95a/1e3cc06cb4fd07fbd5fb3b0fcd0c9fbf/ndp48-devpack-enu.exe'
        $output = 'dotnet_framework.exe'
        $webClient.DownloadFile($url, $output)
        Start-Process -FilePath $output -ArgumentList '/q' -Wait

    - name: Setup .NET Framework 4.8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # specify your tag name
        release_name: Release v1.0.0  # specify your release name
        body: |
          Release notes for v1.0.0:
          - Describe your changes here
        draft: false
        prerelease: false
