name: Publish Windows Forms App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2  # This will set up the MSBuild tool

      - name: Build
        run: |
          nuget restore Codeformer.sln
          msbuild /p:Configuration=Release Codeformer.csproj

      - name: Publish
        run: |
          msbuild /t:Publish /p:Configuration=Release /p:Platform="Any CPU" Codeformer.sln

      - name: List files before zip
        run: |
          dir ${GITHUB_WORKSPACE}

      - name: Create Zip
        run: | 
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::CreateFromDirectory("D:\a\codeformer-DotNetWrapper\codeformer-DotNetWrapper\bin\Release\app.publish", "D:\a\codeformer-DotNetWrapper\codeformer-DotNetWrapper\Codeformer-Dotnet.zip")
        
      - name: List files after zip
        run: |
          dir ${GITHUB_WORKSPACE}
          
      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/1.0/assets?name=Codeformer-Dotnet.zip
          asset_path: D:\a\codeformer-DotNetWrapper\codeformer-DotNetWrapper\Codeformer-Dotnet.zip
          asset_name: Codeformer-Dotnet.zip
          asset_content_type: application/zip
