name: Publish Windows Forms App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2  # This will set up the MSBuild tool

    - name: Build
      run: |
        nuget restore Codeformer.sln
        msbuild /p:Configuration=Release Codeformer.csproj

    - name: Publish
      run: |
        msbuild /t:Publish /p:Configuration=Release /p:Platform="Any CPU" Codeformer.sln
    - name: List files before tar
      run: |
        ls -al ${GITHUB_WORKSPACE}
    - name: Create Zip
      run: | 
        tar.exe -a -c -f ${GITHUB_WORKSPACE}\Codeformer-Dotnet.zip D:\a\codeformer-DotNetWrapper\codeformer-DotNetWrapper\bin\Release\app.publish
        
    - name: List after before tar
      run: |
        ls -al ${GITHUB_WORKSPACE}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
        name: Codeformer-Dotnet # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: Codeformer-Dotnet.zip


          
