name: Publish Windows Forms App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2  # This will set up the MSBuild tool

      - name: Build
        run: |
          nuget restore Codeformer.sln
          msbuild /p:Configuration=Release Codeformer.csproj

      - name: Publish
        run: |
          msbuild /t:Publish /p:Configuration=Release /p:Platform="Any CPU" Codeformer.sln

      - name: Create Release
        id: create_release
        run: |
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" `
                     -Headers @{
                       Authorization = "token $env:GITHUB_TOKEN"
                       Content-Type = "application/json"
                     } `
                     -Method POST `
                     -Body '{
                       "tag_name": "dfc86763007179801fde20bec0592190a62b9c70",
                       "name": "Release dfc86763007179801fde20bec0592190a62b9c70",
                       "draft": false,
                       "prerelease": false
                     }'

          $release_id = $response.id
          Write-Output "Release ID is $release_id"

      - name: List files before tar
        run: |
          dir ${GITHUB_WORKSPACE}

      - name: Create Zip
        run: | 
          tar.exe -a -c -f D:\a\codeformer-DotNetWrapper\codeformer-DotNetWrapper\Codeformer-Dotnet.zip D:\a\codeformer-DotNetWrapper\codeformer-DotNetWrapper\bin\Release\app.publish
        
      - name: List after before tar
        run: |
          dir ${GITHUB_WORKSPACE}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${{ steps.create_release.outputs.release_id }}/assets?name=Codeformer-Dotnet.zip
          asset_path: ${GITHUB_WORKSPACE}\Codeformer-Dotnet.zip
          asset_name: Codeformer-Dotnet.zip
          asset_content_type: application/zip
