name: Publish Windows Forms App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2  # This will set up the MSBuild tool

    - name: Build
      run: |
        nuget restore Codeformer.sln
        msbuild /p:Configuration=Release Codeformer.csproj

    - name: Publish
      run: |
        msbuild /t:Publish /p:Configuration=Release /p:Platform="Any CPU" Codeformer.sln

